env:
  browser: false
  es2021: true
extends:
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  import/extensions: [0, { <js>: "always" }],
  'no-console': 'off'
}

